site_name: Kriten
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/kriten-io
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/EvolvereDevOps
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/evolvere-technologies

copyright: |
  &copy; 2024 <a href="https://github.com/kriten-io"  target="_blank" rel="noopener">Evolvere Technologies</a>
