site_name: kriten
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/kriten-io
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/kubecode-limited
    - icon: fontawesome/brands/slack
      link: https://netdev-community.slack.com/archives/C06PJKB2HUJ

markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      
nav:
  - Installation: "index.md"
  - Why Kriten?: "why.md"
  - Overview: "overview.md"
  - User Guide:
    - Getting Started: "user_guide/getting_started.md"
    - Manage Secrets: "user_guide/manage_secrets.md"
    - Role Based Access Control: "user_guide/rbac.md"
    - API Tokens: "user_guide/api_tokens.md"
    
copyright: |
  &copy; 2024 <a href="https://github.com/kriten-io"  target="_blank" rel="noopener">Kubecode Limited</a>
